// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDkxtMwfslajG4wuy07C6COJfnmGcylUos',
    appId: '1:905611628396:web:0497b949053252eb10ad49',
    messagingSenderId: '905611628396',
    projectId: 'tibibti-d52f7',
    authDomain: 'tibibti-d52f7.firebaseapp.com',
    storageBucket: 'tibibti-d52f7.firebasestorage.app',
    measurementId: 'G-V01Y8C27J4',
    databaseURL: 'https://tibibti-d52f7-default-rtdb.firebaseio.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCOnSBeZaJfAf6hpKSWCqttXD4aN2VL2Uo',
    appId: '1:905611628396:android:b542e21d80bfedb510ad49',
    messagingSenderId: '905611628396',
    projectId: 'tibibti-d52f7',
    storageBucket: 'tibibti-d52f7.firebasestorage.app',
    databaseURL: 'https://tibibti-d52f7-default-rtdb.firebaseio.com',
  );


  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAk1Ckwf1T7n0CHOzA1PYv_hUbWmo7fGXg',
    appId: '1:905611628396:ios:be88f10a3c1921ad10ad49',
    messagingSenderId: '905611628396',
    projectId: 'tibibti-d52f7',
    storageBucket: 'tibibti-d52f7.firebasestorage.app',
    iosClientId: '905611628396-jcm88r1cisr11dc3drk2iv658i5ga4sb.apps.googleusercontent.com',
    iosBundleId: 'com.example.tibibti',
    databaseURL: 'https://tibibti-d52f7-default-rtdb.firebaseio.com',
  );
}
